### PR TITLE
PL target state="translated"

### PR DESCRIPTION
**Pull request by DonSqueak**
I was bored ;)

### CODE REVIEW

**Comment by DonSqueak** [comment]
FYI, all I did was insert the line break and add the state="translated"

From experience, this helps *immensely* with merge conflicts with the upstream.

**Comment by spitfire** [comment]
Thanks a lot!

I've merged this, but GitHub still says there are conflicts.
Did you script it/use sed or something like that?

**Comment by DonSqueak** [comment]
> I've merged this, but GitHub still says there are conflicts. Did you script it/use sed or something like that?

Yeah, for some reason I did it starting at line 30 or so. Don't ask me why, I was tired :D

**Comment by DonSqueak** [comment]
I guess if you add the few missing line breaks, the conflicts should resolve themselves. It's always between `</source>` and `<target>`.

**Comment by DonSqueak** [comment]
@spitfire I added another Pull Request

**Pull request merged**
